---
# This playbook is used to build or update NLnet Unbound image
# Based on Alpine version {{version.alpine}} and exported as: {{docker_tag}}
# All related configuration is placed in the file db.yml

- name: Update NLnet Labs Unbound image
  hosts: localhost
  gather_facts: yes

  vars:
    yml_db: ./cfg/db.yml


  tasks:
  - name: "MAIN:> Include: {{yml_db}}"
    ansible.builtin.include_vars:
      file: "{{yml_db}}"
      name: db



#  - name: Prepare nsd.conf from template 
#    template:
#      src: ./template/nsd.conf.j2
#      dest: ./nsd.conf


  - name: "MAIN:> Include: {{db.yml_pre_task}}"
    ansible.builtin.include_tasks:
      file: "{{db.yml_pre_task}}"


  - name: "MAIN:> Include: {{db.yml_check}}"
    ansible.builtin.include_tasks:
      file: "{{db.yml_check}}"
  

  - name: "MAIN:> Include: {{db.yml_build}}"
    ansible.builtin.include_tasks:
      file: "{{db.yml_build}}"
      

#  - name: "MAIN:> Include: {{db.yml_update}}"
#    ansible.builtin.include_tasks:
#      file: "{{db.yml_update}}"